export const StepTypes = {
  VISIT_NODE: "VISIT_NODE",
  RELAX_EDGE: "RELAX_EDGE",
  UPDATE_DISTANCE: "UPDATE_DISTANCE",
  HIGHLIGHT_PATH: "HIGHLIGHT_PATH",
  COLOR_NODE: "COLOR_NODE",
  COLOR_EDGE: "COLOR_EDGE",
  UPDATE_LABEL: "UPDATE_LABEL",
  ADD_NODE: "ADD_NODE",
  ADD_EDGE: "ADD_EDGE",
  REMOVE_EDGE: "REMOVE_EDGE",
  CLEAR_GRAPH: "CLEAR_GRAPH" ,
  INFLUENCE_NODE: "INFLUENCE_NODE",
  SET_LABEL: "SET_LABEL"
  
};