export const StepTypes = {
  // Core traversal
  VISIT_NODE:       'VISIT_NODE',
  RELAX_EDGE:       'RELAX_EDGE',
  UPDATE_DISTANCE:  'UPDATE_DISTANCE',
  HIGHLIGHT_PATH:   'HIGHLIGHT_PATH',
  FINAL_PATH_NODE:  'FINAL_PATH_NODE',
  FINAL_PATH_EDGE:  'FINAL_PATH_EDGE',
  COLOR_NODE:       'COLOR_NODE',
  COLOR_EDGE:       'COLOR_EDGE',
  UPDATE_LABEL:     'UPDATE_LABEL',
  INFLUENCE_NODE:   'INFLUENCE_NODE',
  SET_LABEL:        'SET_LABEL',
  WAIT:             'WAIT',

  // Graph generation
  ADD_NODE:         'ADD_NODE',
  ADD_EDGE:         'ADD_EDGE',
  REMOVE_EDGE:      'REMOVE_EDGE',
  CLEAR_GRAPH:      'CLEAR_GRAPH',
  APPLY_LAYOUT:     'APPLY_LAYOUT',

  // Structural Balance
  BALANCE_ASSIGN_NODE:  'BALANCE_ASSIGN_NODE',
  BALANCE_VISIT_EDGE:   'BALANCE_VISIT_EDGE',
  BALANCE_EDGE_OK:      'BALANCE_EDGE_OK',
  BALANCE_EDGE_CONFLICT:'BALANCE_EDGE_CONFLICT',
  BALANCE_EDGE_FLIP:    'BALANCE_EDGE_FLIP',
  PULSE_EDGE:           'PULSE_EDGE',

  // Ranking
  RANK_NODE:        'RANK_NODE',
  HITS_NODE:        'HITS_NODE',
  ITERATION_BADGE:  'ITERATION_BADGE',
};
